### ISSUE TITLE
BUG: macOS and Windows minor misc issues

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-installers#90]
Overall the installation process was quite nice on macOS! A couple of minor issues:

1. At the end on macOS, the installer popped up a notification saying I could access MNE-Python via applications. Ideally clicking this would open the folder `/Applications/MNE-Python`, but instead it popped up the script editor (?):

   <img width="812" alt="Screen Shot 2022-03-18 at 3 09 58 PM" src="https://user-images.githubusercontent.com/2365790/159069220-9247164e-378c-4ad1-80c9-1d15f26686ae.png">
 
2. When I open the command prompt app, it prints out more stuff than it probably should (first few lines), almost like a `Makefile` without at `@` preceding each command:

    <img width="1082" alt="Screen Shot 2022-03-18 at 3 12 19 PM" src="https://user-images.githubusercontent.com/2365790/159069310-1734607e-5fdc-4243-8d9b-07361cafa259.png">

3. All of the app names are too long:

    <img width="635" alt="Screen Shot 2022-03-18 at 3 14 27 PM" src="https://user-images.githubusercontent.com/2365790/159069986-9e513960-fe89-4dc5-ad08-066f53e78b85.png">

    If at all possible, it might be better to trim the version (it could be in the App name instead maybe?), and/or since they're already in a folder called MNE-Python, the `"MNE "` from the beginning of each app could be trimmed. I think it's implied each one will be our app's variant by it being in the MNE-Python app folder. (Naive users won't care, and expert users will expect / understand that things are sandboxed/organized like this.)

    The same goes for windows, where the version shows up in the folder, but then every app has both "MNE " and the version at the end, which is redundant:

    ![Capture](https://user-images.githubusercontent.com/2365790/159073868-b98e4d70-b671-4998-9630-b277aaed18f4.PNG)

**Comment by larsoner** [comment]
Updated to mention the same minor naming issue on Windows, where other than that, things worked as expected!

**Comment by larsoner** [comment]
... except one more thing that I just noticed -- the uninstaller on Windows *does* remove all the files from `~/mne-python/` (good) but it *does not* remove the start menu entries (bad):

![Capture2](https://user-images.githubusercontent.com/2365790/159074996-30c7a940-bbec-4c64-9fa7-70f57975b295.PNG)

**Comment by hoechenberger** [comment]
Thank you for testing the installer on 3 platforms!!!



> 1. At the end on macOS, the installer popped up a notification saying I could access MNE-Python via applications. Ideally clicking this would open the folder `/Applications/MNE-Python`, but instead it popped up the script editor (?):

The notifications are displayed via AppleScript. Unfortunately, this also means when you click on them, the script editor will be brought up.

I have to say that on my systems, I usually don't even see those notifications as I'm in Do Not Disturb mode.

My proposal would be to just remove them.

WDYT?



> 2\. When I open the command prompt app, it prints out more stuff than it probably should (first few lines), almost like a `Makefile` without at `@` preceding each command:

Oh, yes, I never looked into that. If you believe this is an issue, it should be fixed here:

- [for Linux](https://github.com/conda-forge/mne-feedstock/blob/dev/recipe/menu/open_prompt.sh)
- [for macOS](https://github.com/conda-forge/mne-feedstock/blob/dev/recipe/menu/open_prompt.applescript) (even though I wouldn't know **how** to fix it … because again, we're using AppleScript to pipe those commands into the terminal 🤔)




> 3\. All of the app names are too long:

If you open the folder "properly" in Finder, it should display correctly though, right?

These popup file browser windows from the Dock are notorious for not providing enough space for the filenames! I have this problem will all kinds of documents. This is why I usually never use this functionality.

<img width="700" alt="Screen Shot 2022-03-19 at 08 52 40" src="https://user-images.githubusercontent.com/2046265/159112825-d6ea1b4f-4a21-4abd-993e-242d864bc343.png">



> 3\. If at all possible, it might be better to trim the version (it could be in the App name instead maybe?), and/or since they're already in a folder called MNE-Python, the `"MNE "` from the beginning of each app could be trimmed. I think it's implied each one will be our app's variant by it being in the MNE-Python app folder. (Naive users won't care, and expert users will expect / understand that things are sandboxed/organized like this.)

The reason I did do it this way is really to avoid confusion in case users are relying on Spotlight to find & open their apps (after switching to macOS, this is how I start my apps 100% of the time!)

If the app was just called, say, `Spyder`, it wouldn't be immediately clear that it's the one we shipped (the user would have to check in which folder it's located).

Applications are ranked higher in the results than folders, so those apps get a higher "visual priority":

<img width="827" alt="Screen Shot 2022-03-19 at 08 49 21" src="https://user-images.githubusercontent.com/2046265/159112681-9f312b23-60ff-417d-aa1f-bf3386c65c15.png">

The version number is appended to allow parallel installs of different versions.

I could imagine dropping the version numbers from the file names, and appending it to the MNE-Python **folder** in `/Applications` instead…

**But this approach wouldn't transfer to Linux,** where on the Ubuntu desktop (Unity, I suppose?) all shortcuts end up in a single launcher without hierarchies, so the only way to communicate different version numbers if different installations is by adding those numbers to the shortcuts. And also prepending MNE IMHO becomes a necessity there, otherwise our shortcuts are just "Spyder", "Prompt", "System Info", which doesn't make sense without additional context.



> 3\. The same goes for windows, where the version shows up in the folder, but then every app has both "MNE " and the version at the end, which is redundant:

Yes, this one we should probably try to fix.



> the uninstaller on Windows _does_ remove all the files from `~/mne-python/` (good) but it _does not_ remove the start menu entries (bad):

Interesting, the last time I tested with @GuillaumeFavelier, the start menu entries were removed – only the desktop icons remained. Speaking of which – do you think we need desktop icons, or should we disable them?

**Comment by larsoner** [comment]
> My proposal would be to just remove them.

Yes, better to remove it than have it pop up something that doesn't make sense when it's clicked.

> Oh, yes, I never looked into that. If you believe this is an issue, it should be fixed here:
>
> * [for Linux](https://github.com/conda-forge/mne-feedstock/blob/dev/recipe/menu/open_prompt.sh)

On Linux and Windows it was okay actually. Just a macOS problem.

> If you open the folder "properly" in Finder, it should display correctly though, right? ... (after switching to macOS, <spotlight> is how I start my apps 100% of the time!)

Yes, there and in Spotlight it's okay. But I think it's important to make sure finder, spotlight, *and* the dock are as usable as possible.

Right now it's `MNE <app> (<version>)`, but perhaps we should prioritize the actual app name. Seeing `MNE Spy... dev)` as the name in the dock is less informative than `Spyder (M...dev)` or however it would look if we changed it to `<app> (MNE <version>)`. This will still look fine in Spotlight, even if MNE shows up later in the name, so I think it's a net usability gain:

| Spotlight | Dock |
| -- | -- |
| <img width="792" alt="Screen Shot 2022-03-19 at 7 30 56 AM" src="https://user-images.githubusercontent.com/2365790/159119386-f62cc99e-4259-4257-b2c6-55fae9734a89.png"> | <img width="643" alt="Screen Shot 2022-03-19 at 7 32 37 AM" src="https://user-images.githubusercontent.com/2365790/159119434-c0169363-ff1f-4499-8272-4749123b4ac7.png"> |

And having the version just in the folder looks even better to me:

| Spotlight | Dock |
| -- | -- |
| <img width="792" alt="Screen Shot 2022-03-19 at 7 46 39 AM" src="https://user-images.githubusercontent.com/2365790/159119824-8c85d50b-1ac8-41b6-8e89-3f2e03a57de3.png"> | <img width="646" alt="Screen Shot 2022-03-19 at 7 46 53 AM" src="https://user-images.githubusercontent.com/2365790/159119840-3efa096f-398a-428a-83f7-d7ca48d818fe.png"> |

> The version number is appended to allow parallel installs of different versions.

Sure, but let's keep in mind that 1) this will be rarer than the standard single-install case, 2) I doubt people will keep multiple versions for very long, and 3) even when they do, name resolution is only a problem in Spotlight. It would be a shame to make the simultaneous-install-and-spotlight use case reduce the usability of the much more common single-MNE-app-install-or-not-spotlight cases. That said, having "Spyder (MNE)" does at least make "mne" in spotlight resolve properly. And if we're going to keep MNE in there, I can live with keeping the version number there, too, if you think it's really important. I'll let you decide...

> I could imagine dropping the version numbers from the file names, and appending it to the MNE-Python folder in /Applications instead… But this approach wouldn't transfer to Linux

FWIW, it's already inconsistent between macOS and Windows (see screenshots above) -- on macOS the dock/Application folder is just MNE-Python, on Windows the Start Menu folder is "MNE-Python (1.0dev0)".

I think we should do whatever makes the presentation cleanest on each OS. For Windows and macOS, my preference would be having the start menu / Applications folder be "MNE-Python (1.0dev0)", and the app names have the highest priority at least as above. For Linux -- where there is no "folder" -- I'm fine with "<app> (MNE 1.0dev0)" or "MNE <app> (1.0dev)" (though I think I prefer the former).

> Speaking of which – do you think we need desktop icons, or should we disable them?

Sometimes it's an option in installers. I'd remove them until (if ever) we find a way to make it optional.

**Comment by hoechenberger** [comment]
> > 2. When I open the command prompt app, it prints out more stuff than it probably should (first few lines), almost like a `Makefile` without at `@` preceding each command:
[...]
> * [for macOS](https://github.com/conda-forge/mne-feedstock/blob/dev/recipe/menu/open_prompt.applescript) (even though I wouldn't know **how** to fix it … because again, we're using AppleScript to pipe those commands into the terminal 🤔)

I just spent 30 min to find a solution and I don't think there is an easy one.

I am planning to add iTerm2 support in a future version of the installer (it has a [Python scripting interface](https://iterm2.com/python-api/)) – I believe this is time better spent.

Thoughts?

**Comment by larsoner** [comment]
Ultimately I don't think the printing is so bad. Could it be simplified by adding a little script with those two commands, then you just call the script? Then what gets printed would at least be much shorter and fit on one line

**Comment by larsoner** [comment]
I think we can close this and open targeted issues in the future following changes in `main` and in #195
